### ISSUE TITLE
Database connects but does not update

### ISSUE THREAD

**Issue by NellicusLabs** [brycematheson/timeclock#1]
I have gotten your time clock setup but when I go to add a new user it does not get inserted into the database. I am not getting any kind of errors.

**Comment by brycematheson** [comment]
Hi Justin,

I apologize that my time clock application isn't working correctly for you right off the bat. Although there are a few issues with my application, the main functionality should be there and it should be working. I'm fairly swamped with other things at the moment, but I'll try and get a chance to take a look at this sometime soon.

Thanks for your interest in my application,
Bryce

**Comment by brycematheson** [comment]
Justin,

If you're still interested, go ahead and take a look at the new version of the application. It's mostly the same, but with minor bug fixes here and there, as well as some minor functionality changes.
